import type { Project } from "./schema";

export const projects: Project[] = [
// export const projects = [
  {
    id: "1",
    title: "CodeBlue",
    description: "Modern corporate website with 9 color themes, responsive design, and portfolio showcase",
    fullDescription: "CodeBlue is a comprehensive corporate website solution featuring a dynamic theme system that allows users to personalize their experience with 9 distinct color schemes. Built with modern web technologies, it provides a fully responsive design that adapts seamlessly across all devices.",
    image: "../client/public/projects/codecircle.png",
    // image: "C:/Users/ElvinOfTheMazwiClan/Documents/GitHub/MPS/client/public/projects/codecircle.png",
    gallery: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["HTML5", "CSS3", "Bootstrap", "jQuery"],
    category: "corporate",
    badges: ["Featured"],
    features: [
      "9 customizable color themes",
      "Fully responsive design",
      "Portfolio showcase section",
      "Contact form integration",
      "Smooth animations and transitions",
    ],
    challenges: "The main challenge was implementing a theme system that maintained accessibility standards across all 9 color schemes while ensuring smooth transitions.",
    outcome: "Successfully delivered a versatile corporate website template that has been adopted by multiple businesses, receiving positive feedback for its customization options.",
    liveDemo: "#",
    githubUrl: "#",
  },
  {
    id: "2",
    title: "PremiumCars",
    description: "Comprehensive car dealership platform with inventory management and contact integration",
    fullDescription: "PremiumCars is a full-featured car dealership platform designed to streamline the vehicle browsing and purchasing experience. The platform includes sophisticated inventory management, advanced search and filtering capabilities, and integrated contact systems.",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["HTML5", "CSS3", "PHP", "JavaScript"],
    category: "ecommerce",
    badges: ["Automotive", "E-commerce"],
    features: [
      "Dynamic inventory management",
      "Advanced search filters",
      "Vehicle comparison tool",
      "Integrated contact system",
      "Image galleries for each vehicle",
    ],
    challenges: "Implementing an efficient filtering system that could handle large inventories while maintaining fast page load times.",
    outcome: "The platform successfully manages over 500 vehicle listings with instant search and filter results, improving customer engagement by 40%.",
    liveDemo: "#",
    githubUrl: "#",
  },
  {
    id: "3",
    title: "BuildCorp",
    description: "Professional construction company website with project galleries and service showcases",
    fullDescription: "BuildCorp is a professional website for construction companies featuring extensive project galleries, service showcases, and client testimonials. Built with performance and visual appeal in mind.",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["HTML5", "CSS3", "JavaScript", "AOS"],
    category: "corporate",
    badges: ["Construction", "Professional"],
    features: [
      "Project portfolio gallery",
      "Service showcase pages",
      "Client testimonials section",
      "Scroll-triggered animations",
      "Mobile-optimized image galleries",
    ],
    challenges: "Optimizing image-heavy content for fast loading while maintaining high visual quality across all devices.",
    outcome: "Achieved a 95+ PageSpeed score while showcasing high-resolution project imagery, leading to increased client inquiries.",
    liveDemo: "#",
    githubUrl: "#",
  },
  {
    id: "4",
    title: "DataFlow",
    description: "IoT and analytics platform with real-time data visualization and industry solutions",
    fullDescription: "DataFlow is an enterprise-grade IoT analytics platform providing real-time data visualization and insights for industrial applications. Features comprehensive dashboards and customizable reporting tools.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1543286386-2e659306cd6c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["HTML5", "CSS3", "JavaScript", "Charts.js"],
    category: "dashboard",
    badges: ["Analytics", "IoT"],
    features: [
      "Real-time data visualization",
      "Customizable dashboards",
      "Multi-device support",
      "Export functionality",
      "Alert notifications",
    ],
    challenges: "Implementing real-time data updates without performance degradation, especially when handling thousands of data points.",
    outcome: "Platform now processes over 10,000 data points per second with smooth visualization updates, serving multiple enterprise clients.",
    liveDemo: "#",
    githubUrl: "#",
  },
  {
    id: "5",
    title: "AdminPro",
    description: "Professional admin dashboard with multiple themes and comprehensive management features",
    fullDescription: "AdminPro is a versatile admin dashboard template featuring multiple pre-built themes, comprehensive data management tools, and customizable widgets for various business needs.",
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["HTML5", "CSS3", "JavaScript", "Bootstrap"],
    category: "dashboard",
    badges: ["Dashboard", "Multi-theme"],
    features: [
      "Multiple theme options",
      "Responsive data tables",
      "Chart and graph widgets",
      "User management system",
      "Role-based access control",
    ],
    challenges: "Creating a flexible theme system that could be easily customized while maintaining consistent component behavior.",
    outcome: "AdminPro has been used as the foundation for over 50 different admin interfaces, saving development teams significant time.",
    liveDemo: "#",
    githubUrl: "#",
  },
  {
    id: "6",
    title: "Personal Portfolio",
    description: "Personal portfolio website with blog system and project showcase",
    fullDescription: "A modern personal portfolio built with Gatsby featuring a blog system, project showcases, and Progressive Web App capabilities for optimal performance and offline access.",
    image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1516321497487-e288fb19713f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    technologies: ["Gatsby", "React", "GraphQL", "PWA"],
    category: "portfolio",
    badges: ["Personal", "Blog"],
    features: [
      "Static site generation with Gatsby",
      "GraphQL data layer",
      "Progressive Web App",
      "Markdown blog system",
      "SEO optimized",
    ],
    challenges: "Implementing a performant GraphQL data layer while maintaining fast build times as content grew.",
    outcome: "Achieved perfect Lighthouse scores across all metrics and serves content to users within milliseconds globally via CDN.",
    liveDemo: "#",
    githubUrl: "#",
  },
];
